### ISSUE TITLE
ASDF not found when starting plain vanilla Lispworks

### ISSUE THREAD

**Issue by joelreymont** [emotiq/emotiq#290]
README need instructions to `(require 'asdf)`.

**Comment by easye** [comment]
Note that this is only necessary when running LispWorks or ABCL.

**Comment by joelreymont** [comment]
This should be documented, regardless of where it's needed.

**Comment by echupriyanov** [comment]
I've installed completely from scratch macOS and LispWorks 7.1.1
There is no need to explicitly `(require 'asdf)`

**Comment by easye** [comment]
@echupriyanov Add to a `lispworks.md`?
