### ISSUE TITLE
no match TxID warning

### ISSUE THREAD

**Issue by guitarvydas** [emotiq/emotiq#438]
This warning is intermittent and not yet reproducible.
It appears to be generated by new-transactions.lisp and might be related to find-transaction-per-id (also in new-transactions.lisp).

**Comment by dbmcclain** [comment]
Honestly, I think you need to scrutinize and rewrite portions of new-transactions.lisp. I don't understand the notions of "being like Bitcoin", and "not wanting to modify Mark D's code", being sacrosanct. We need this system to behave properly, and if junk code in new-transactions.lisp is causing problems, then you should feel free to re-engineer the code.

**Comment by dbmcclain** [comment]
I think these kinds of errors stem from API's that are too loose and accepting of args without checking for proper tags on the data. The best way to protect your code is to use defmethod with specializers on the expected argument tags. Defun's with simple named args are a bad idea here.

**Comment by dbmcclain** [comment]
In attempting to be too much like Bitcoin, I think Mark D. erred in the direction of observing binary only data. Keys and hashes as mere vectors of bytes. Bad idea. Maybe that's all C could manage, but we have LOENC:ENCODE which can record tags as well as data, as well as composite structures with known class / structure types. We should be taking advantage of all that Lisp can offer beyond C, and stop living in the "like Bitcoin" straightjacket.
