### ISSUE TITLE
Forgot to sign warning

### ISSUE THREAD

**Issue by guitarvydas** [emotiq/emotiq#439]
" 2018-08-15 09:51:32 WARN Transaction missing witness data. Forgot to sign? Rejected."

intermittent, might be benign

**Comment by dbmcclain** [comment]
Whoa! How the heck can a block be interned into the blockchain without a BFT number of signatures? That sounds like an error of logic in the Leader node. Should always have a BFT threshold or else just drop and await a new election.

**Comment by guitarvydas** [comment]
It says "rejected".  I've been assuming (without further investigation) that the transaction is thrown away.
